#!/usr/bin/env python3
"""Build a scoped offline cache including both directory and index.html visits."""
import hashlib
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1] / "build/web"
worker = root / "index.service.worker.js"
files = sorted(p.name for p in root.iterdir()
               if p.is_file() and p.name != worker.name
               and p.suffix in {".html", ".js", ".wasm", ".pck", ".png", ".json"})
digest = hashlib.sha256()
for name in files:
    digest.update(name.encode())
    digest.update((root / name).read_bytes())
version = digest.hexdigest()[:16]
source = """// Generated by tools/finalize_web.py. Do not edit the exported copy.
const PREFIX = `little-nook:${self.registration.scope}:`;
const CACHE = PREFIX + VERSION;
const FILES = ASSETS;
self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE)
    .then(cache => cache.addAll(FILES))
    .then(() => self.skipWaiting()));
});
self.addEventListener('activate', event => {
  event.waitUntil(caches.keys()
    .then(keys => Promise.all(keys.filter(key => key.startsWith(PREFIX) && key !== CACHE)
      .map(key => caches.delete(key))))
    .then(() => self.clients.claim()));
});
self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET' ||
      !event.request.url.startsWith(self.registration.scope)) return;
  event.respondWith(caches.open(CACHE).then(async cache => {
    // Directory URLs and index.html identify the same game, including offline.
    if (event.request.mode === 'navigate') {
      const index = await cache.match('index.html');
      if (index) return index;
    }
    return (await cache.match(event.request, {ignoreSearch: true})) || fetch(event.request);
  }));
});
// Godot sends these lifecycle messages to its configured worker.
self.addEventListener('message', event => {
  if (event.origin !== self.location.origin) return;
  if (event.data === 'claim' || event.data === 'update') {
    event.waitUntil(self.skipWaiting().then(() => self.clients.claim()));
  }
});
"""
worker.write_text(source.replace("VERSION", json.dumps(version)).replace("ASSETS", json.dumps(files)))
print(f"Offline cache prepared: {len(files)} assets, version {version}.")
